Can climb and changed shooting range to enum
Team1690/Scouting-2024 pull request #115
Opened 2024-03-12 08:24 UTC by BOSSkabab

2024-03-12 13:58 UTC, itamarsch requested changes

2024-03-12 13:58 UTC, itamarsch commented on lib/views/mobile/screens/pit_view/pit_toggle.dart
> +        onPressed: (final int i) => setState,
You don't call the function here this widget does nothing

2024-03-12 13:58 UTC, itamarsch commented on lib/views/mobile/screens/pit_view/pit_toggle.dart
> +  final List<bool> isSelected;
Make selected a bool

2024-03-12 13:58 UTC, itamarsch commented on lib/views/mobile/screens/pit_view/pit_toggle.dart
> +  final void Function() setState;
Call this onPressed instead

2024-03-13 11:30 UTC, BOSSkabab commented on lib/views/mobile/screens/pit_view/pit_toggle.dart
> +        onPressed: (final int i) => setState,
but i don't use i in the setState

2024-03-13 11:30 UTC, BOSSkabab commented on lib/views/mobile/screens/pit_view/pit_toggle.dart
> +        onPressed: (final int i) => setState,
but i don't use i in the setState

2024-03-13 15:33 UTC, merged