Team info fix
Team1690/Scouting-2024 pull request #35
Opened 2024-02-07 21:54 UTC by IdoDePro

2024-02-07 22:16 UTC, itamarsch requested changes

2024-02-07 22:16 UTC, itamarsch commented on lib/views/pc/team_info/widgets/gamechart/gamechart_card.dart
> +                        p0.technicalMatchData!.data.gamepieces,
Don't you mean data.technicalMatches currently nothing says this isn't null?

2024-02-07 22:16 UTC, itamarsch commented on lib/views/pc/team_info/widgets/gamechart/gamepiece_line_chart.dart
> +                  .toList(),
This isn't always correct to use fullGames you should think about cases where there is a specific match but there isn't a technical match or otherwise

2024-02-08 08:13 UTC, IdoDePro commented on lib/views/pc/team_info/widgets/gamechart/gamechart_card.dart
> +                        p0.technicalMatchData!.data.gamepieces,
so it accepts match data and not technical matches

2024-02-08 20:07 UTC, merged