Coach team info
Team1690/Scouting-2024 pull request #48
Opened 2024-02-14 15:46 UTC by IdoDePro

basic coach team info still need to add auto data maybe?

2024-02-15 18:27 UTC, itamarsch requested changes

2024-02-15 18:27 UTC, itamarsch commented on lib/views/mobile/screens/coach_team_info/coach_team_info_line_charts.dart
> +        //TODO add linecharts
TODO?

2024-02-15 18:27 UTC, itamarsch commented on lib/views/mobile/screens/coach_team_info/coach_team_info_data.dart
> +            if (snapshot.hasError) {
mapSnapshot?

2024-02-15 18:27 UTC, itamarsch commented on lib/views/mobile/screens/coach_team_info/coach_team_info_data.dart
> +                              QuickData(
What happened to QuickData from TeamData?

2024-02-15 18:27 UTC, itamarsch commented on lib/views/mobile/screens/coach_team_info/coach_quick_data.dart
> +  Widget build(final BuildContext context) => data.amoutOfMatches == 0
Try to find a way to combine the quick data in team info and we can probably remove some fields

2024-02-15 18:27 UTC, itamarsch commented on lib/views/mobile/screens/coach_team_info/coach_auto_data.dart
> +                      children: <Widget>[], //TODO add season specific data
What is this file?

2024-02-18 19:56 UTC, IdoDePro commented on lib/views/mobile/screens/coach_team_info/coach_auto_data.dart
> +                      children: <Widget>[], //TODO add season specific data
not relevant yet until chayko finishes auto screen

2024-02-19 16:55 UTC, itamarsch approved these changes

2024-02-19 17:50 UTC, merged